language: java
jdk: openjdk8
services:
  - docker

install: true
addons:
  sonarcloud:
    organization: $ORGANIZATION_KEY
    token:
      secure: $SONAR_TOKEN

stages:
  - name: test
  - name: sonar_analysis
  - name: build_image
    if: branch = master

jobs:
  include:
    - stage: test
      script: mvn clean test
    - stage: sonar_analysis
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=notification-service
    - stage: build_image
      before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      script:
        - mvn clean install dockerfile:build -Dmaven.test.skip=true -Ddocker.image.name=$IMAGE_NAME;
        - docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_NAME;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_NAME;
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache