language: java
jdk: openjdk8
services:
  - docker
script: mvn clean install dockerfile:build
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker images
  - docker pull $DOCKER_USERNAME/$DOCKER_REPOSITORY
  - docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY
  - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY
cache:
  directories:
    - $HOME/.m2