language: java
jdk: openjdk8
services:
  - docker

stages:
  - test
  - name: build

jobs:
  include:
    - stage: test
      script: mvn clean test
    - stage: build
      before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      script:
        - mvn clean install dockerfile:build -Dmaven.test.skip=true -Ddocker.image.name=$IMAGE_NAME
        - docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_NAME;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_NAME;
cache:
  directories:
    - $HOME/.m2