language: java
jdk: openjdk8
services:
  - docker
script: mvn clean install dockerfile:build
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TAG_NAME;
      docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$TAG_NAME;
    fi
cache:
  directories:
    - $HOME/.m2