version: '3.5'
services:

  notification-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: notification-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - notification-pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}

  notification-service:
    image: notification-service
    container_name: notification-service
    command: ["/wait-for-it.sh", "notification-db:5432", "--timeout=${DB_CONTAINER_WAIT_TIMEOUT}", "--", "java", "-jar", "notification-service.war"]
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8082:8080"
    networks:
      - default
    depends_on:
      - notification-db

networks:
  default:
    name: app-network
    driver: bridge

volumes:
  notification-pgdata:
    name: notification-pgdata