version: '3.5'
services:

  notification-db:
    image: postgres:9.6.9
    container_name: notification-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - notification-pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Novosibirsk"
      PGTZ: "Asia/Novosibirsk"

  notification-service:
    image: notification-service
    container_name: notification-service
    command: ["/wait-for-it.sh", "notification-db:5432", "--timeout=45", "--", "catalina.sh", "run"]
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8443:8443"
    networks:
      - default
    depends_on:
      - notification-db

networks:
  default:
    name: app-network
    driver: bridge

volumes:
  notification-pgdata:
    name: notification-pgdata