spring:
  ## Email properties
  mail:
    host: smtp.gmail.com
    port: 25
    username: rbatsw@gmail.com
    password: 1953s50w42i65m14015
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: false
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mail
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

mailConfig:
  maxFailedAttemptsToSent: 10
  pageSize: 10
  delaySeconds: 10

webServiceConfig:
  wsdlConfig:
    portTypeName: NotificationPort
    locationUri: /ws
    targetNamespace: http://schemas.xmlsoap.org/soap/envelope/
  xsdSchema: notification.xsd