global:
  scrape_interval: 10s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
       insecure_skip_verify: true
    static_configs:
      - targets: ['notification-service:8443']